# Generated by Django 5.0.6 on 2024-05-31 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0006_remove_bookinstance_imprint_bookinstance_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='book',
            new_name='book_title',
        ),
    ]
