# Generated by Django 5.0.6 on 2024-05-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0008_alter_bookinstance_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='book_title',
            new_name='title',
        ),
    ]
