# Generated by Django 5.0.6 on 2024-05-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0009_rename_book_title_bookinstance_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='reader_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
